stages:
  - genLicense
  - checkLicense
  - build_sample
  - build_module
  - build_feature
  - build_master
  - clean_build
  - plainPW_check
  - cov
  - fossid
  - release_customize_sdk

genLicense:
  variables:
    CODE_COMPILE_ARCH: 'TC32'
    COV_PF_CATALOG: 'BLE'
  stage: genLicense
  tags:
    - LINUX
  before_script:
  script:
    - date
    - generat_license_list
    - date
  artifacts:
    paths:
    - "license_list_gen.txt"
    - "no_license_list_gen.txt"
    - "mismatch_license_file_gen.txt"
  when: manual
  
checkLicense:
  variables:
    CODE_COMPILE_ARCH: 'TC32'
    COV_PF_CATALOG: 'BLE'
  stage: checkLicense
  tags:
    - LINUX
  allow_failure: yes
  before_script:
  script:
    - date
    - check_license
    #- generat_license_list # For no license files
    - date
  artifacts:
    when: always
    paths:
    - "mismatch_license.txt"
    - "no_license*.txt"
    - "unknow_type_file.txt"

build_sample:
  stage: build
  tags:
    - LINUX
    - TC32
  before_script:
  script:
    - which tc32-elf-gcc
    - chmod +x b80_ble_sdk/*.sh
    - date
    - $TC32_ECLIPSE_BUILD  -data ${CI_PIPELINE_ID}_WS  -import ./b80_ble_sdk/  -cleanBuild telink_b80_ble_single_connection_sdk/8208_ble_sample
    - date

  artifacts:
    paths:
    - "b80_ble_sdk/8208_ble_sample/*.bin"
    - "b80_ble_sdk/8208_ble_sample/*.lst"
    - "b80_ble_sdk/8208_ble_sample/*.elf"

build_module:
  stage: build
  tags:
    - LINUX
    - TC32
  before_script:
  script:
    - which tc32-elf-gcc
    - chmod +x b80_ble_sdk/*.sh
    - date
    - $TC32_ECLIPSE_BUILD  -data ${CI_PIPELINE_ID}_WS  -import ./b80_ble_sdk/  -cleanBuild telink_b80_ble_single_connection_sdk/8208_module
    - date

  artifacts:
    paths:
    - "b80_ble_sdk/8208_module/*.bin"
    - "b80_ble_sdk/8208_module/*.lst"
    - "b80_ble_sdk/8208_module/*.elf"

build_feature:
  stage: build
  tags:
    - LINUX
    - TC32
  before_script:
  script:
    - which tc32-elf-gcc
    - chmod +x b80_ble_sdk/*.sh
    - date
    - $TC32_ECLIPSE_BUILD  -data ${CI_PIPELINE_ID}_WS  -import ./b80_ble_sdk/  -cleanBuild telink_b80_ble_single_connection_sdk/8208_feature_test
    - date

  artifacts:
    paths:
    - "b80_ble_sdk/8208_feature_test/*.bin"
    - "b80_ble_sdk/8208_feature_test/*.lst"
    - "b80_ble_sdk/8208_feature_test/*.elf"
    
build_master:
  stage: build
  tags:
    - LINUX
    - TC32
  before_script:
  script:
    - which tc32-elf-gcc
    - chmod +x b80_ble_sdk/*.sh
    - date
    - $TC32_ECLIPSE_BUILD  -data ${CI_PIPELINE_ID}_WS  -import ./b80_ble_sdk/  -cleanBuild telink_b80_ble_single_connection_sdk/8208_master
    - date

  artifacts:
    paths:
    - "b80_ble_sdk/8208_master/*.bin"
    - "b80_ble_sdk/8208_master/*.lst"
    - "b80_ble_sdk/8208_master/*.elf"

clean_build:
  stage: clean_build
  tags:
    - LINUX
    - TC32
  script:
    - ls -a
    - rm -r * .git*
    - ls -a
  when: always
  
plainPW_check:
  stage: plainPW_check 
  tags:
    - LINUX
  script:
    - echo "Enter Plain Password checking stage"
    - check_plain_weak_password | tee result.txt
    - ls -l result.txt
    - echo "Error List:"
    - cat result.txt
  artifacts:
    paths:
    - result.txt
  when: manual

# The cov job definition
cov:
  variables:
    CODE_COMPILE_ARCH: 'TC32'
    COV_PF_CATALOG: 'BLE'
  stage: cov
  tags:
    - COV    
    - LINUX    
    - TC32
  before_script:
  script:
    - chmod +x b80_ble_sdk/*.sh
    - $COV_B COV_$CI_PROJECT_NAME $COV_B_TEMPLATE/$CODE_COMPILE_ARCH $TC32_ECLIPSE_BUILD  -data ${CI_PIPELINE_ID}_WS  -import ./b80_ble_sdk -cleanBuild b80_ble_sdk/8208_ble_sample
    - $COV_A COV_$CI_PROJECT_NAME 
    - cov_add_commit_steam_project_2_platform.sh
  when: manual

fossid:
  tags:
    - FOSSID
  stage: fossid
  script:
    - fossid_check.sh
  artifacts:
    paths:
    - fossid*.txt
  when: manual

.release_sdk_template: &release_sdk_template
  variables:
    PACK_NAME: "release_sdk_template"
  stage: release_customize_sdk	
  tags:
    - windows_tc32_test
  script:
    - sdk_release_customize.sh ./release_sdk_config
  artifacts:
    name: "$PACK_NAME"
    expire_in: '3 yrs'
    paths:
    - "./b80_ble_sdk"
    - "./README.md"
    - "./doc"
  when: manual

release_sdk_S1:
  <<: *release_sdk_template
  variables:
    PACK_NAME: "telink_b80_ble_single_connection_sdk_V3.4.1.2_S1"

release_sdk_S2:
  <<: *release_sdk_template
  variables:
    PACK_NAME: "telink_b80_ble_single_connection_sdk_V3.4.1.2_S2"

release_sdk_S3:
  <<: *release_sdk_template
  variables:
    PACK_NAME: "telink_b80_ble_single_connection_sdk_V3.4.1.2_S3"

release_sdk_custom_made_S0:
  <<: *release_sdk_template
  variables:
    PACK_NAME: "telink_b80_ble_single_connection_sdk_V3.4.1.2_custom_made_S0"

release_sdk_custom_made_S1:
  <<: *release_sdk_template
  variables:
    PACK_NAME: "telink_b80_ble_single_connection_sdk_V3.4.1.2_custom_made_S1"

release_sdk_custom_made_S2:
  <<: *release_sdk_template
  variables:
    PACK_NAME: "telink_b80_ble_single_connection_sdk_V3.4.1.2_custom_made_S2"

release_sdk_custom_made_S3:
  <<: *release_sdk_template
  variables:
    PACK_NAME: "telink_b80_ble_single_connection_sdk_V3.4.1.2_custom_made_S3"
